### ISSUE TITLE
Amendment Suggestion

### ISSUE THREAD

**Issue by Ritu1611** [lukew3/mathgenerator#123]
@lukew3 why do we need different generator, one for surface area then one for volume of a solid. Can't we just merge both of them together.

**Comment by lukew3** [comment]
I think that it's best if their kept seperate so that when a user asks for a problem they know exactly what they are going to get. Although surface area and volume are usually taught at the same time, I think that it would still make sense to keep them seperate in case a student needs to practice just one skill and not another.
