### ISSUE TITLE
Multiplication favors a large first factor and small second factor

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#300]
**Name or Id of generator:**
id 2 - multiplication
**Issue:**
First factor of problem is some number between 1 and 100 while second number is a number between 0 and 3 usually. They should be equally likely to get a larger or smaller number. Maximum value of a factor should probably be smaller and maybe have the location of a and b in the problem vary.

**Comment by Nitsujed** [comment]
It looks like in the code section below, there is an if statement that unless ```a==0```, which is rare, the else statement has a `min()` function looking for `99/a`. This is leading to `min()` resolving to very little numbers since as `a` grows, `99/a` decreases exponentially. Not sure why this if/else exists. I'm assuming the original intent was to prevent a problem of 0*0, but if thats the case the logic is wrong regardless. Proposed solution below, and I'd be happy to make the change. Though I think removing the if/else is a better solution...

Original Code:
```   python
    a = random.randint(0, maxMulti)
    if a == 0:
        b = random.randint(0, maxRes)
    else:
        b = random.randint(0, min(int(maxMulti / a), maxRes))
```

Proposed Code:
``` python
    a = random.randint(0, maxMulti)
   #though I'm not sure there should be an if/else at all 
   if a == 0:
        b = random.randint(1, maxRes)
    else:
        b = random.randint(0, maxRes))```
