### ISSUE TITLE
Saner division exercises

### ISSUE THREAD

**Issue by matkoniecz** [lukew3/mathgenerator#332]
**Name or Id of generator:** 3

**Issue:** example from readme reveals problem with that task: `67/85=  0.788235294117647`

1) it is extremely hard and obnoxious and frustrating for someone learning to divide
2) division-focused exercise are unlikely to be useful for anyone else

I would propose to switch to integer only results or to something that has no more than N decimal places.

Or have separate "division, integer output task".

This example in readme looks really silly.

**Comment by lukew3** [comment]
Thanks for bringing attention to this issue. A whole number division already existed before this issue was proposed. However, it was strange that the whole number division generator was created after the long decimal division generator. To fix this, I set the division generate to generate whole number solutions and created a new generator called complex_division that generates division problems that can possible have decimal answers which are rounded to the hundredths place after calculation.
