### ISSUE TITLE
CalcuLaTeX Integration

### ISSUE THREAD

**Issue by mkhan45** [lukew3/mathgenerator#398]
It would be neat if the templates were paired with [CalcuLaTeX](https://github.com/mkhan45/CalcuLaTeX) solutions such that a LaTeX solution with steps could be autogenerated. I can help get it started if you would like

**Comment by lukew3** [comment]
That looks like a cool tool, but I don't think it's what I'm going for with this project. I'd rather have a straightforward problem and answer generator and leave the process to be taught by teachers and curriculum creators. I also want it to be a solely python library so that I'm not forcing people into using other tooling.
