### ISSUE TITLE
Find intersection of two lines

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#66]
Example Problem:
Find the point of intersection of these two lines: y = (1/2)x + 6, y = 2x-2.
Example Solution:
((16/3),(26/3))

Given the form y = mx + b, m and b should be between -10 and 10.

**Comment by akashsara** [comment]
I'll take this up, please assign it to me.

Also it's possible that the generated lines are parallel and so have no intersection, what should be done in this case? Should we regenerate the problem or should the solution be something like "No Intersection"?

**Comment by SubahanM** [comment]
i would like to contribute

**Comment by lukew3** [comment]
@akashsara I think that there should be the possibility of parallel lines included. "No Intersection" would be a good way to express the solution.

**Comment by akashsara** [comment]
Alright. Another question - does this require fractions as well? While I think it'll make things a bit more complicated, you've given a fraction in the example. If fractions are allowed for either m, b or both, what are the restrictions on the fractions?

On another note, is it maybe time to consider separating out the `mathgen.py` file? As more and more generators are added, it'll get a bit messy. In addition, submitting PRs might be an issue since any PR that is merged would cause conflicts with other PRs since they're all modifying the same file.

**Comment by lukew3** [comment]
> does this require fractions as well?

I think that m should contain fractions, not b though. Fractional slopes are often found in this type of problem. Plus, if slopes were only integers, the point of intersections would be very far from the origin. I'd say limit the denominator to 6 perhaps.
> On another note, is it maybe time to consider separating out the mathgen.py file?

I was thinking about this too. Do you have any suggestions? Maybe it could be modularized by subject like algebra, geometry, early math, calculus, etc.

**Comment by akashsara** [comment]
> I think that m should contain fractions, not b though. Fractional slopes are often found in this type of problem. Plus, if slopes were only integers, the point of intersections would be very far from the origin. I'd say limit the denominator to 6 perhaps.

Alrighty, then I'll keep a ~50% chance of m being a fraction where the denominator is from 1-6~ and the numerator is -10 to 10. I'll just let it choose a denominator from 1-6, if it's 1 it just becomes a whole number.

> I was thinking about this too. Do you have any suggestions? Maybe it could be modularized by subject like algebra, geometry, early math, calculus, etc.

I was thinking more of having one file per generator and then group the generators (files) in some way. The subject-wise method you mentioned is one possible option. Since the user will obviously know what kind of problem they want, subject-wise organization also means the user will be able to do a sort of search where they choose their subject and then problem.

**Comment by lukew3** [comment]
Issue #99 opened

**Comment by prajjval30-zz** [comment]
I would like to contribute

**Comment by helplessThor** [comment]
I would like to contribute, please assign it to me, i'm an advanced python coder

**Comment by akashsara** [comment]
@prajjval30 @helplessThor the issue has been resolved and the PR merged. Do take a look at the other open issues in the repo though.
